site_name: blast2galaxy Documentation
repo_name: blast2galaxy
repo_url: https://github.com/IPK-BIT/blast2galaxy
edit_uri: edit/main/docs/

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Tutorial: tutorial.md
  - CLI Reference: cli.md
  - API Reference: api.md

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.highlight

plugins:
  - mkdocstrings


markdown_extensions:
  - attr_list
  - mkdocs-click
  - admonition
  - pymdownx.details
  - pymdownx.superfences