name: Tests
on: push
jobs:
  tests:
    name: Run tests
    environment: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    #- name: Set up Python
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: '3.12'

    - name: Setup miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        miniforge-version: latest
        channels: bioconda,conda-forge
        channel-priority: true

    - run: |
        conda info
        conda env list
        conda config --show-sources
        conda activate test

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.8.3

    - name: Install project with Poetry
      run: poetry install --compile

    - name: Run pip list and conda list
      run: |
        pip list
        conda list

    #- name: Run nox
    #  run: poetry run nox

    - name: Create .blast2galaxy.toml
      env:
        API_KEY_GALAXY_WEB_IPK: ${{secrets.API_KEY_GALAXY_WEB_IPK}}
        API_KEY_USEGALAXYEU: ${{secrets.API_KEY_USEGALAXYEU}}
      run: |
        echo "api_key = \"$API_KEY_GALAXY_WEB_IPK\"" >> ~/.blast2galaxy.toml
        cat ~/.blast2galaxy.toml

    - name: Run tests
      run: poetry run pytest -s tests/
